### PR TITLE
Add a switch to polygon button if user on another network

### PR DESCRIPTION
**Pull request by har777**
#224

### CODE REVIEW

**Comment by gglucass** [comment]
@har777 mmm might be nice if we can add it in the item that displays the current network 🤔 ?

**Comment by Syncretik** [comment]
@gglucass there is similar logic in the `BuyingGuideModal` but you said just changing the network won't update the balance,

> no it's pulling the balance on the mainnet RPC for the testnet contract address, which will always be zero

still not sure what this means, do we need additional logic/params in addition to `useSwitchNetwork` in both places?

**Comment by gglucass** [comment]
> @gglucass there is similar logic in the `BuyingGuideModal` but you said just changing the network won't update the balance,
> 
> > no it's pulling the balance on the mainnet RPC for the testnet contract address, which will always be zero
> 
> still not sure what this means, do we need additional logic/params in addition to `useSwitchNetwork` in both places?

balance not updating has already been resolved and now works. I do not understand your question.

**Comment by Syncretik** [comment]
this is not resolved I think you're talking about a different issue.

https://www.loom.com/share/20c0d262f4184408b46f4788326d1d22?sid=f290c3f9-5a57-4419-bc8e-9230591b0652

**Comment by gglucass** [comment]
> this is not resolved I think you're talking about a different issue.
> 
> https://www.loom.com/share/20c0d262f4184408b46f4788326d1d22?sid=f290c3f9-5a57-4419-bc8e-9230591b0652

yeah on local stuff doesn't work because we don't have the right contracts set up. It works on app.glodollar.org now.

**Review by Syncretik — APPROVED** [review]

**Review by Riglanto — APPROVED** [review]

**Pull request merged**
