### PR TITLE
Add a "switch to polygon" step

### PR DESCRIPTION
**Pull request by har777**

### CODE REVIEW

**Comment by har777** [comment]
@gglucass Do we need a button to switch to polygon? Given the app automatically does that on-load anyway?

**Review by Riglanto — APPROVED** [review]

**Comment by gglucass** [comment]
> @gglucass Do we need a button to switch to polygon? Given the app automatically does that on-load anyway?

Yes let's make it as easy as possible for the user to explicitly switch to Polygon if they haven't already. We've seen in testing that it happens more easily than you might expect. People can also reject switching for instance.

Maybe we can check for the current connected network and only show that switcher when a user _isn't_ connected to it?

**Comment by har777** [comment]
> > @gglucass Do we need a button to switch to polygon? Given the app automatically does that on-load anyway?
> 
> Yes let's make it as easy as possible for the user to explicitly switch to Polygon if they haven't already. We've seen in testing that it happens more easily than you might expect. People can also reject switching for instance.
> 
> Maybe we can check for the current connected network and only show that switcher when a user _isn't_ connected to it?

Should we show the step at all if user is already on polygon then?

**Comment by gglucass** [comment]
> Should we show the step at all if user is already on polygon then?

We can skip if the user is already on Polygon :-)

**Review by gglucass — APPROVED** [review]

**Pull request merged**
