### PR TITLE
refactor/design feedback

### LINKED ISSUE #106: Design requests
- [x] Hey it's Jeff --> Hey, it's Jeff
- [x] Social login on one line
- [x] Let’s make sure that the spacing between the different boxes (glowallet (image 1)) is much more like the current calculator on our homepage. It looks better + we don’t use necessary space.
- [x] The spacing between ‘Transactions’ and ‘No transactions to show’ can be reduced by 50%.
- [x] I think ‘Balance’ is a bit too close to $0.00. Maybe should add 3px extra.
- [x] Let’s drop the shadow from the Log in button. Instead let’s colours, font size etc from the adopt Glo Dollar button in our navigation on the website.
- [x] Let's make sure the font sizes are in line with the sizes in the Figma designs
- [x] The text that would show below ‘Help Grow Glo’ I think we can already show greyed out AND/OR with a notification text that reads: ‘Log in first’ -> pending #119 to implement
- [x] ‘Hey it’s Jeff’ can be reduced 30-45%.
- [x] Consider using a real image here. I think it’d be cool to make this Emily as the emails the user would follow would also be from ‘Emily from Glo’ [WILL NOT DO]
- [x] Also let’s drop the cyan outline if we do that
- [x] The light cyan used for the $0 / year (#DEFAF8) I think is a new colour introduced. Could we instead use the same colour as in the impact calculator (#24E5DF as bg) and (#123C38) for the text?
- [x] Next to the ‘Log in’ we could add a circle with a question mark that opens the Notion FAQ in a new page?
- [x] Show wallet address next to the avatar button, rather than in the middle
- [x] Mobile: Move "Buy 1000 Glo on Uniswap" to be above the "Enough to buy:" steps
- [x] Show Help Grow Glo CTA contents on non logged in accounts? -> #119 

Started a bit here: https://github.com/Glo-Foundation/glo-wallet/pull/105

### PR DESCRIPTION
**Pull request by Syncretik**
resolves #106, #122

### CODE REVIEW

**Comment by gglucass** [comment]
Mm my balance isn't getting updated @Syncretik - this wallet has 842 test USDGLO - maybe some state update not firing anymore?

image

**Comment by gglucass** [comment]
@Syncretik small icon alignment issue on mobile 
IMG_98D0642039AD-1

**Comment by Syncretik** [comment]
ugh I don't see it in responsive devtools >:( is it chromium browser?

Screen Shot 2023-06-20 at 5 50 43 AM

**Comment by gglucass** [comment]
> ugh I don't see it in responsive devtools or my own phone (pixel 6) >:( is it chromium browser?
> 
> Screen Shot 2023-06-20 at 5 50 43 AM

No it's just iOS safari :-( Maybe try browserstack?

**Comment by Syncretik** [comment]
ran out of my free 1 min, should we get a plan? trying [mabl](https://www.mabl.com/software-test-automation-trial?utm_source=google&utm_medium=cpc&utm_campaign=branded-wd&utm_adgroup=&gad=1&gclid=Cj0KCQjwnMWkBhDLARIsAHBOftrZO73roGStg1CwQfq-L4Fs-k3g3h5iZycRS2oNjPJuKYzocEOi27MaAlPmEALw_wcB) now

**Comment by Syncretik** [comment]
@gglucass so mabl doesn't suit our purposes but I changed the icon class to our button component for horizontal/vertical centering, can you check to see if it lines up now?

**Review by gglucass — APPROVED** [review]

**Pull request closed without merging**
